name: build

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'packages/**'

  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'packages/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.6.0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run compile and build packages
        run: pnpm build
